### ISSUE TITLE
Update function name

### ISSUE THREAD

**Issue by tanzeeldev** [i-huzaifa-arshad/Soccer-Game-API#3]
Functon name should be some action like `buy_player()`  or `show_transfer_list()`

https://github.com/i-huzaifa-arshad/Soccer-Game-API/blob/ca51dc1919c1341f9dcc1bee6152d7955b6935e0/api/helper.py#L50

**Comment by i-huzaifa-arshad** [comment]
Fixed

**Comment by i-huzaifa-arshad** [comment]
Fixed.
