### ISSUE TITLE
Update variable name

### ISSUE THREAD

**Issue by tanzeeldev** [i-huzaifa-arshad/Soccer-Game-API#4]
Use descriptive variable names to enhance code readability. `obj` to be updated to some meaningful name

https://github.com/i-huzaifa-arshad/Soccer-Game-API/blob/ca51dc1919c1341f9dcc1bee6152d7955b6935e0/api/helper.py#L62

**Comment by i-huzaifa-arshad** [comment]
Fixed. Also updated function name for better readability.

**Comment by i-huzaifa-arshad** [comment]
Fixed. Also updated function name for better readability and added `player_id` field as well.
